#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <windows.h>
#include <fstream>
#include <string>
#include <algorithm>
#include <vector>
#include <iomanip>
#include <set>
#include <map>
#include "Accounts.h"
#include "Cards.h"
#include "Categories.h"
#include "Date.h"
#include "Expenses.h"
#include "functions.h"
#include "Report.h"
#include "ReportGenerator.h"
#include "Time.h"
#include "Wallets.h"